# Generated by Django 5.0.7 on 2024-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super-admin', 'Super-Admin'), ('admin', 'Admin'), ('finance', 'Finance'), ('supervisor', 'Supervisor'), ('staff', 'Staff')], default='super-admin', max_length=20),
        ),
    ]
