# Generated by Django 5.0.7 on 2024-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='Developer', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.CharField(blank=True, default='Chibuikem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.CharField(blank=True, default='HI', max_length=155, null=True),
        ),
    ]
